### ISSUE TITLE
Display Pop-Ups for Embedded Maps

### ISSUE THREAD

**Issue by RoxanneFaure** [Digital-Humanities-Quarterly/dhq-journal#13]
The maps for 000652 have the following minor issues:

- Informational popups are not appearing when elements of the map are clicked on. It looks like this on DHQ when an area is selected:
![figure10_splitscreen_nopopup](https://user-images.githubusercontent.com/89929318/205410572-e0beffc2-aeba-4e5b-b0fe-adb158599636.png)
And here's the map on the website, showing popup:
![original_with_popup](https://user-images.githubusercontent.com/89929318/205410583-62fc3366-96a8-4d16-9f51-60d9caf3ac3f.png)

- The full map is visible in fullscreen, but not in splitscreen. The window gets smaller, but the map stays the same size and scroll bars appear for navigating the map. This means the search bar and zoom button are not always visible in splitscreen. The current plan is to contact the author to see if they want to add any instructions to the article explaining this navigation, but it can also be left as is.

**Comment by jawalsh** [comment]
For the first bullet point, I think you are comparing two different maps (Figure 10 and Figure 11). I believe those are two different maps, with different code, rather than two views of the same map/code. I can't find an example of the top map on the authors' project web site. So I can't compare to see if our DHQ version is working like theirs. However, for Figure 11. There is definitely a problem. The layers control is not showing up. I will investigate to see if I can figure out what's working with that. The pop-ups are working, for me at least. So if we can get the layers control to work, I think it will be ok.

For the second bullet point, regarding controls not being visible in the iframe and forcing users to scroll to see the controls, Julia and I recommend adding a note to the caption. Something like: "Interface controls may be hidden depending on the size of your browser window. Scroll within the iFrame or open the map in a new window to access interface controls."

**Comment by RoxanneFaure** [comment]
Thank you! I've added a note to the captions for Figures 10 and 11.

**Comment by jawalsh** [comment]
I believe the issue with Figure 11 is now fixed. The layers are displaying.
